version: '3.9'

services:
  web:
    build:
      context: .  
      dockerfile: php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/html  
      - ../app/uploads:/var/www/html/uploads  
      

    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: multi_login
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
